engines:
  brakeman:
    enabled: true
    checks:
      validation_regex:
        enabled: false
  rubocop:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
          mass_threshold: 30
      - javascript
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- test/**
- spec/**
- vendor/**
- "public/assets/**/*"